version: '3'

services:
  mssql:
    hostname: FoodTruckApi
    image: "microsoft/mssql-server-linux:latest"
    environment:
      SA_PASSWORD: "passWord_123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
